// ui/angular/src/app/my-case-list/my-case-list.component.ts
import { Component, OnInit, AfterViewInit, ViewChild  } from '@angular/core';
import { Router } from '@angular/router';
import { MatPaginator, PageEvent } from '@angular/material';

import { MyCaseService } from '../shared/my-case/my-case.service';

@Component({
  selector: 'app-my-case-list',
  templateUrl: './my-case-list.component.html',
  styleUrls: ['./my-case-list.component.css']
})
export class MyCaseListComponent implements OnInit, AfterViewInit {
	myCaseList: Array<any>;
	pageItem: {};
	dataSource: [];
	tableColumns:  string[] = [
		"title", 
		"status", 
		"caseType1", 
		"caseType2", 
		"caseType3", 
		"statusCode", 
		"comments", 

		"id"
	];
	
	@ViewChild(MatPaginator) paginator: MatPaginator;
	
	constructor(private router: Router, 
			private myCaseService: MyCaseService) { }
	
	ngOnInit() {
		this.gotoPage(this.paginator.pageIndex);
			//this.myCaseList = data[0].content;
			//this.pageItems = data[0];
//			 "pageable" : {
//				    "sort" : {
//				      "sorted" : false,
//				      "unsorted" : true,
//				      "empty" : true
//				    },
//				    "offset" : 0,
//				    "pageSize" : 25,
//				    "pageNumber" : 0,
//				    "paged" : true,
//				    "unpaged" : false
//				  },
//				  "last" : false,
//				  "totalPages" : 8,
//				  "totalElements" : 199,
//				  "size" : 25,
//				  "number" : 0,
//				  "sort" : {
//				    "sorted" : false,
//				    "unsorted" : true,
//				    "empty" : true
//				  },
//				  "first" : true,
//				  "numberOfElements" : 25,
//				  "empty" : false
		
	}
	
	ngAfterViewInit() {
		this.paginator.page.pipe().subscribe(()=>this.loadPage());
	}
	
	loadPage(){
		this.gotoPage(this.paginator.pageIndex);
	}
	
	gotoPage(pageNumber){
		console.info("gotoPage: pageNumber=>" + pageNumber);
		this.myCaseService.getAll(pageNumber, this.paginator.pageSize).subscribe(data => {
			this.dataSource = data.myCaseList.content;
			this.paginator.pageSize=data.myCaseList.pageable.pageSize;
			this.paginator.pageIndex=data.myCaseList.pageable.pageNumber;
			this.paginator.length=data.myCaseList.totalElements;
		});
	}

	remove(id) {
		this.myCaseService.remove(id).subscribe(result => {
			this.loadPage();
		}, error => console.error(error));
	}
}



<mat-card>
<mat-card-header> <mat-card-title>
	<h2>MyCase List</h2>
	</mat-card-title> </mat-card-header>
<mat-card-actions>
<a mat-raised-button [routerLink]="['/my-case-add']" color="primary">New</a>
<mat-paginator [pageSizeOptions]="[10, 25, 50]" #matPaginator1></mat-paginator>
</mat-card-actions>
<mat-card-content> 
<mat-table [dataSource]="dataSource">
	<mat-header-row *matHeaderRowDef="tableColumns"></mat-header-row>
	<mat-row *matRowDef="let myRowData; columns: tableColumns"></mat-row>
	<!--
	<ng-container  matColumnDef="status">
		<mat-header-cell *matHeaderCellDef>Status</mat-header-cell>
		<mat-cell *matCellDef="let myRowData">{{myRowData.status? myRowData.status.description:''}}</mat-cell>
	</ng-container>
	-->
	<ng-container  matColumnDef="title">
		<mat-header-cell *matHeaderCellDef>Title</mat-header-cell>
		<mat-cell *matCellDef="let myRowData">{{myRowData.title}}</mat-cell>
	</ng-container>
	<ng-container  matColumnDef="status">
		<mat-header-cell *matHeaderCellDef>Status</mat-header-cell>
		<mat-cell *matCellDef="let myRowData">{{myRowData.status.value}}</mat-cell>
	</ng-container>
	<ng-container  matColumnDef="caseType1">
		<mat-header-cell *matHeaderCellDef>Case Type 1</mat-header-cell>
		<mat-cell *matCellDef="let myRowData">{{myRowData.caseType1.value}}</mat-cell>
	</ng-container>
	<ng-container  matColumnDef="caseType2">
		<mat-header-cell *matHeaderCellDef>Case Type 2</mat-header-cell>
		<mat-cell *matCellDef="let myRowData">{{myRowData.caseType2.value}}</mat-cell>
	</ng-container>
	<ng-container  matColumnDef="caseType3">
		<mat-header-cell *matHeaderCellDef>Case Type 3</mat-header-cell>
		<mat-cell *matCellDef="let myRowData">{{myRowData.caseType3.value}}</mat-cell>
	</ng-container>
	<ng-container  matColumnDef="statusCode">
		<mat-header-cell *matHeaderCellDef>Status Code</mat-header-cell>
		<mat-cell *matCellDef="let myRowData">{{myRowData.statusCode.value}}</mat-cell>
	</ng-container>
	<ng-container  matColumnDef="comments">
		<mat-header-cell *matHeaderCellDef>Comments</mat-header-cell>
		<mat-cell *matCellDef="let myRowData">{{myRowData.comments}}</mat-cell>
	</ng-container>
	
	<ng-container  matColumnDef="id">
		<mat-header-cell *matHeaderCellDef>Action</mat-header-cell>
		<mat-cell *matCellDef="let myRowData">
			<a mat-button [routerLink]="['/my-case-detail', myRowData.id]">Edit</a>
			<a mat-button (click)="remove(myRowData.id)">Delete</a>
		</mat-cell>
	</ng-container>
</mat-table>
</mat-card-content>
<mat-card-actions>
<a mat-raised-button [routerLink]="['/my-case-add']" color="primary">New</a>
</mat-card-actions>
</mat-card>

// ui/react/src/forms/myCase/MyCaseListComponent.jsx
import React from 'react';

import Typography from '@material-ui/core/Typography';
import { Table, TableHead, TableRow, TableCell, Button, TableBody, TablePagination } from '@material-ui/core';
import MyCaseService from '../../api/myCase/MyCaseService';

class MyCaseListComponent extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      list: [],
      paging: {
        rowsPerPage: 25,
        totalElements: 0,
        currentPage: 0
      }
    }
  }
  componentDidMount = () => {
    this.retrieve();
  }
  retrieve = () => {
    MyCaseService.getList(this.state.paging.currentPage, this.state.paging.rowsPerPage)
      .then(response => {
        console.log(response)
        this.setState({
			list: response.data.myCaseList.content ,
			paging: {
	            rowsPerPage: response.data.myCaseList.size,
	            totalElements: response.data.myCaseList.totalElements,
	            currentPage: response.data.myCaseList.pageable.pageNumber
			}
		})
      })
  }
  edit = (id) => {
    console.log(`[MyCaseComponent.edit] id=${id}`)
    this.props.history.push(`/my-case-detail/${id}`);
  }
  delete = (id) => {
    console.log(`[MyCaseComponent.delete] id=${id}`)
	MyCaseService.delete(id)
      .then(response => {
        console.log(`[MyCaseComponent.delete] response==>`, response)
        this.retrieve();
      })
  }

  handleChangePage = (e, newPage) => {
    //this.state.paging.currentPage = newPage;
	let paging = this.state.paging;
	paging.currentPage = newPage
	this.setState({
		paging: paging
	});
    this.retrieve();
  }
  handleChangeRowsPerPage = (e) => {
	let paging = this.state.paging;
	paging.rowsPerPage = e.target.value
	paging.currentPage = 0;
	this.setState({
		paging: paging
	});
    this.retrieve();
  }

  render = () => {
    return (
      <div className="container">
        <Typography variant="h4">MyCase List</Typography>
        <Button variant="contained" color="primary" onClick={() => this.edit(-1)}>NEW</Button>
        <TablePagination
          component="div"
          count={this.state.paging.totalElements}
          page={this.state.paging.currentPage}
          onChangePage={this.handleChangePage}
          rowsPerPage={this.state.paging.rowsPerPage}
          onChangeRowsPerPage={this.handleChangeRowsPerPage}
        />
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>Title</TableCell>
              <TableCell>Status</TableCell>
              <TableCell>Case Type 1</TableCell>
              <TableCell>Case Type 2</TableCell>
              <TableCell>Case Type 3</TableCell>
              <TableCell>Status Code</TableCell>
              <TableCell>Comments</TableCell>

              <TableCell>Action</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {this.state.list.map(row => (
              <TableRow key={row.id}>
                <TableCell>{row.title}</TableCell>
                <TableCell>{row.status.value}</TableCell>
                <TableCell>{row.caseType1.value}</TableCell>
                <TableCell>{row.caseType2.value}</TableCell>
                <TableCell>{row.caseType3.value}</TableCell>
                <TableCell>{row.statusCode.value}</TableCell>
                <TableCell>{row.comments}</TableCell>

                <TableCell align="right">
                  <Button variant="contained" color="primary" onClick={() => this.edit(row.id)}>Edit</Button>&nbsp;
                  <Button variant="contained" color="primary" onClick={() => this.delete(row.id)}>Delete</Button></TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
        <TablePagination
          component="div"
          count={this.state.paging.totalElements}
          page={this.state.paging.currentPage}
          onChangePage={this.handleChangePage}
          rowsPerPage={this.state.paging.rowsPerPage}
          onChangeRowsPerPage={this.handleChangeRowsPerPage}
        />
      </div >
    );
  }
}

export default MyCaseListComponent;
